// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmvoxdeipybikqybmana.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtdm94ZGVpcHliaWtxeWJtYW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyOTk5MDksImV4cCI6MjA1ODg3NTkwOX0.FzIBiv3BQ34Hm94vooo9uZ6skADlVs3XiETT5HhmZG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);